### ISSUE TITLE
Duplicate script tag on the `base.njk` layout template

### ISSUE THREAD

**Issue by d2s** [planetoftheweb/seven#2]
Noticed a duplicate script tag on the `base.njk` layout template.

https://github.com/planetoftheweb/seven/blob/9dcb2660fffb38f768414248265de5979d30dc11/_site/_templates/layouts/base.njk#L14

That similar code line is loaded on the development environment, but not for the on the production builds. Problem is that currently the build will include a duplicate script tag, causing web browsers to load two different versions of vue library. That will slow down the page load, and potentially cause issues because of the version differences.

https://github.com/planetoftheweb/seven/blob/9dcb2660fffb38f768414248265de5979d30dc11/_site/_templates/layouts/base.njk#L19-L23

The issue is also visible on the official [Seven](https://7ty.tech/) website.

```html
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <!-- ... unrelated code removed ... -->

      <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js"></script>
```

Recommended way to fix this would be to remove the `line 14` from the `base.njk` layout file.

**Comment by planetoftheweb** [comment]
Yeah...nice catch. I'm recording some stuff right now, but I'll fix this when I get a chance.

**Comment by planetoftheweb** [comment]
Adressed in the next 'carouselupdate'
